name: "release"

# see https://stackoverflow.com/questions/67501652/github-workflow-event-trigger-synchronize-not-working
on: 
  push:
    tags:
      - "*"
  pull_request:
    types: [ opened, edited, synchronize ]
jobs:
  luarocks-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nvim-neorocks/luarocks-tag-release@easier-prs
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          name: nvim-treesitter-test
          version: 0.1
          license: apache 2
          detailed_description: |
            The goal of nvim-treesitter is both to provide a simple and easy way to use the interface for tree-sitter in Neovim
            and to provide some basic functionality such as highlighting based on it.
          template: nvim-treesitter-luarocks.template
